name: setup-node
description: 'Install dependencies 🔧'
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Install dependencies 🔧
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: pnpm install
