name: setup-node
description: 'Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ⚙️
      uses: actions/setup-node@v4

    - name: Cache dependencies ⚡
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Install dependencies 🔧
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: pnpm install
